### ISSUE TITLE
Trouble with Intalling with the latest  R version 3.3.2

### ISSUE THREAD

**Issue by AmberCXX** [danilofreire/prisonbrief#5]
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.3.2 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installing sf
"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/myusername/AppData/Local/Temp/RtmpoT7jKI/devtools1186b5e16e6/r-spatial-sf-83180aa"  \
  --library="C:/Users/myusername/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'sf' ...

ERROR: compilation failed for package 'sf'
* removing 'C:/Users/myusername/Documents/R/win-library/3.3/sf'

**Comment by RobertMyles** [comment]
Hi @AmberCXX , have you tried installing a later version of R? sf is quite a heavy package with quite a few dependencies that you will need to install that are separate to prisonbrief.
@danilofreire we could consider removing sf, what do you think?

**Comment by AmberCXX** [comment]
Updating to the latest version of R solved my issue.

**Comment by AmberCXX** [comment]
Updating to the latest version of R : 
It is successful to install the package using the Rstudio install, which was not an option in my older version.
But installing from github using devtools was not successful in both case mainly due to rtools version. 
-----------------------------------------------------------------------------------------------------------
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 4.0.0 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

**Comment by AmberCXX** [comment]
Additionally, I encounter an new issue with sample code, using the prisonbrief installed by running install.packages("prisonbrief").
--------------------- Code and Error belows.
```
> africa <- wpb_table(region = "Africa")
Error in st_as_sfc.SpatialPolygons(sp::geometry(x), ...) : 
  package rgeos required for finding out which hole belongs to which exterior ring
In addition: Warning message:
Prefixing `UQ()` with the rlang namespace is deprecated as of rlang 0.3.0.
Please use the non-prefixed form or `!!` instead.

  # Bad:
  rlang::expr(mean(rlang::UQ(var) * 100))

  # Ok:
  rlang::expr(mean(UQ(var) * 100))

  # Good:
  rlang::expr(mean(!!var * 100))
```

**Comment by RobertMyles** [comment]
Hi @AmberCXX , you'll need to install rgeos as well, and the correct version of RTools for R v4. I don't use Windows at present, but this might help: https://cran.r-project.org/bin/windows/Rtools/
